---
name: CAM-Template
version: 0.91
author:
  - Clotho Advanced Media, Inc. I<cpan@clotho.com>
abstract: Clotho-style search/replace HTML templates
license: perl
build_requires:
  Test::More: 0
provides:
  CAM::Template:
    file: lib/CAM/Template.pm
    version: 0.91
generated_by: Module::Build version 0.2609
